### PR TITLE
rrfs_ci: Merge in authoritative develop

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 
Merging in all authoritative repository develop changes. 

Please do NOT squash this merge!

## TESTS CONDUCTED: 
None.

## Dependencies:
Please merge simultaneously with NOAA_GSL:regional_workflow [PR #252](https://github.com/NOAA-GSL/regional_workflow/pull/252)

### CODE REVIEW

**Review by christopherwharrop-noaa — APPROVED** [review]

**Review by robgpita — APPROVED** [review]

**Comment by venitahagerty** [comment]
Machine: jet
Compiler: intel
Job: WE
Repo location: /lfs1/BMC/nrtrr/rrfs_ci/autoci/pr/784981740/20211119221559/ufs-srweather-app
Build was Successful
Rocoto jobs started
Done: 0 of 0
If test failed, please make changes and add the following label back:
ci-jet-intel-WE

**Comment by christopherwharrop-noaa** [comment]
@christinaholtNOAA - This is ready to merge, right?

**Comment by christinaholtNOAA** [comment]
@christopherwharrop-noaa I wanted to make sure that @venitahagerty had run all the tests she needed. It looks like both the build on this PR, and the build/WE2E test on the regional_workflow PR succeeded.

Venita, should I merge?

**Comment by venitahagerty** [comment]
Yes, it should be ready to merge.

**Review by robgpita — APPROVED** [review]

**Review by venitahagerty — APPROVED** [review]
Looks good.

**Pull request merged**
