### PR TITLE
RRFS_dev1: Update Hash number for rrfs_utl

### PR DESCRIPTION
**Pull request by hu5970**

### CODE REVIEW

**Review by chunhuazhou — COMMENTED** [review]
Just tried with this new hash but somehow "./devbuild.sh intel"  failed at rrfs_utl/lightning. Not sure if it is just me. Did your build succeed?

**Comment by hu5970** [comment]
I have no problem to compile.

**Review by guoqing-noaa — APPROVED** [review]

**Comment by christopherwharrop-noaa** [comment]
A quick comment.  Were you able to explain @chunhuazhou 's failure?  I only ask because "it works for me, but not for thee" is often indicative of a problem somewhere that needs to be fixed.  I'd recommend against approving PRs before users' issues have been resolved or, at a minimum, explained. This is particularly true in the absence of automated continuous integration testing.

**Comment by hu5970** [comment]
@christopherwharrop-noaa This is not the final package for the release. We will continue working on this package and will fix the problem if it shows up in our next round of deploying in rtrr or personal account.

**Comment by christopherwharrop-noaa** [comment]
Certainly up to your team as to how you want to manage this.  But it's generally a bad idea to merge, and even worse to deploy, code before finding explanations for reviewers' issues and failures.  Revisiting if it shows up after deployment is not a good idea. The whole point of reviews and tests is to catch and fix errors **before** they are deployed.  Maybe we're using the word "deploy" differently.  But in common parlance, if you "deploy" it, it is, by definition, a release because you are putting it into production in an environment in which you care about the results.

**Pull request merged**
