### PR TITLE
Updating UPP hash to point to latest UPP code

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
## DESCRIPTION OF CHANGES: 
This PR updates the UPP hash to use the latest NOAA-GSL code, which includes RAP/HRRR like smoothing for certain fields in RRFS.  Note that it leads to a 40% slowdown in UPP; speeding up the smoothing is left for future work.

## TESTS CONDUCTED: 
The new UPP code was tested in retrospective mode with RRFS_NA_3km domain on Jet.

## DEPENDENCIES:
- NOAA-GSL/UPP/pull/22

## DOCUMENTATION:
None

### CODE REVIEW

**Comment by terraladwig** [comment]
Is there an example of what a field looks like with and without the smoothing? Just curious.

**Comment by EricJames-NOAA** [comment]
@terraladwig yes, Craig helped me create some plots with and without the smoothing.  Not sure the best way to share them...I guess I'll email them to you.

**Comment by hu5970** [comment]
@EricJames-NOAA Did we make decision to use smoothed field from UPP. If so, we need put this PR in current test. Thanks, Ming

**Comment by EricJames-NOAA** [comment]
@hu5970 I'm not sure we decided.  People have asked for the smoothing, but it does currently slow down UPP.  What do you think?  Should we check with a larger group?

**Comment by hu5970** [comment]
@EricJames-NOAA Yes, let's check with the larger group tomorrow. The slow down is not an issue to apply it to RRFS now.

**Comment by EricJames-NOAA** [comment]
@hu5970 sounds good.  Thanks!

**Review by hu5970 — APPROVED** [review]

**Comment by hu5970** [comment]
@EricJames-NOAA I merged this PR. Thanks, Ming

**Comment by EricJames-NOAA** [comment]
@hu5970 thanks!  Please let me know if you see any issues when it is deployed in realtime.

**Pull request merged**
