### PR TITLE
Update hash for the regional workflow

### PR DESCRIPTION
**Pull request by chunhuazhou**
## DESCRIPTION OF CHANGES: 
Update hash for the regional workflow to include the bug fix for calc_ensmean

### CODE REVIEW

**Comment by hu5970** [comment]
@chunhuazhou Could you hold off this update. I will make a PR for regional workflow and we can update the hash together.

**Comment by chunhuazhou** [comment]
> @chunhuazhou Could you hold off this update. I will make a PR for regional workflow and we can update the hash together.

Sure. Let me know when you are ready. Thanks!

**Comment by hu5970** [comment]
@chunhuazhou Could you update this PR to the latest regional workflow hash? Thanks, Ming

**Comment by chunhuazhou** [comment]
> @chunhuazhou Could you update this PR to the latest regional workflow hash? Thanks, Ming

Done. Thanks!

**Review by hu5970 — APPROVED** [review]

**Pull request merged**
