### PR TITLE
Update the pygraf hash for RTMA. 

### PR DESCRIPTION
**Pull request by terraladwig**
Update pygraf hash for RTMA. This includes write capability for skewTs.

## DESCRIPTION OF CHANGES: 
This includes write capability for skewTs.

## DEPENDENCIES:
This is just like PR#147 for RRFS.

### CODE REVIEW

**Review by christinaholtNOAA — APPROVED** [review]

**Comment by guoqing-noaa** [comment]
@terraladwig For RTMA, as least for now, we use the “3DRTMA" branch for real-time runs. Some changes in the "3DRTMA" branch has not committed back to rrfs_dev1 in time yet.

**Comment by christinaholtNOAA** [comment]
@guoqing-noaa You mean you are using a branch in ufs-srweather-app, or in regional_workflow?

I was under the impression that you wouldn't need changes in SRW other than the hashes to the various components, and those are kept in Externals.rtma. Please clarify.

**Comment by guoqing-noaa** [comment]
@christinaholtNOAA  Yes, we also use a "3DRTMA" branch in ufs-srweather-app now because of rapid updates in recent weeks. The main differences to RRFS_dev1 is .github/owners and Externals.rtma.

**Comment by terraladwig** [comment]
I made another PR that is for the 3DRTMA branch... will that work for now?

**Comment by guoqing-noaa** [comment]
Yes, it works.

**Pull request merged**
