### PR TITLE
Enable inline post.

### PR DESCRIPTION
**Pull request by christinaholtNOAA**
## DESCRIPTION OF CHANGES: 
This change allows for the use of the Inline Post with the forecast model, and removes the EMC_Post externals/build. It sets the subset of physics packages that we want to run for the HWT. Lastly, it points to a UFS_UTILS branch that has a fix for running successfully with GEFS initial and boundary conditions.

## Dependencies
This set of mods should be merged along with a PR in the regional_workflow repository.

## TESTS CONDUCTED: 
These changes were tested by @christopherwharrop-noaa and @danielabdi-noaa on AWS, and by Christina on Hera.

## CONTRIBUTORS (optional): 
@christopherwharrop-noaa @danielabdi-noaa

### CODE REVIEW

**Review by christopherwharrop-noaa — APPROVED** [review]
Only nitpick is the removal of newline in the `env/build_aws_intel.env` file.

**Comment by danielabdi-noaa** [comment]
Should we maybe add loading of the correct rocoto in `wflow_aws.env` ? I had to do that manually after fresh cloning of the repository.

**Comment by christinaholtNOAA** [comment]
I can absolutely add that. We haven't historically done that in the repo, but this branch is all about making our lives easier for this project. :)

**Comment by christinaholtNOAA** [comment]
Just to double check, we want this in there, right?
```
module use /contrib/apps/modules
module load rocoto
```

**Comment by danielabdi-noaa** [comment]
> Just to double check, we want this in there, right?
> 
> ```
> module use /contrib/apps/modules
> module load rocoto
> ```

Yes.

**Review by danielabdi-noaa — APPROVED** [review]

**Review by christopherwharrop-noaa — APPROVED** [review]

**Pull request merged**
